// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/ir/serialization.common/src/KotlinIr.proto

package org.jetbrains.kotlin.backend.common.serialization.proto;

public interface IrFileOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.jetbrains.kotlin.backend.common.serialization.proto.IrFile)
    org.jetbrains.kotlin.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated int32 declaration_id = 1 [packed = true];</code>
   */
  java.util.List<java.lang.Integer> getDeclarationIdList();
  /**
   * <code>repeated int32 declaration_id = 1 [packed = true];</code>
   */
  int getDeclarationIdCount();
  /**
   * <code>repeated int32 declaration_id = 1 [packed = true];</code>
   */
  int getDeclarationId(int index);

  /**
   * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.FileEntry file_entry = 2;</code>
   */
  boolean hasFileEntry();
  /**
   * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.FileEntry file_entry = 2;</code>
   */
  org.jetbrains.kotlin.backend.common.serialization.proto.FileEntry getFileEntry();

  /**
   * <code>repeated int32 fq_name = 3 [packed = true];</code>
   */
  java.util.List<java.lang.Integer> getFqNameList();
  /**
   * <code>repeated int32 fq_name = 3 [packed = true];</code>
   */
  int getFqNameCount();
  /**
   * <code>repeated int32 fq_name = 3 [packed = true];</code>
   */
  int getFqName(int index);

  /**
   * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrConstructorCall annotation = 4;</code>
   */
  java.util.List<org.jetbrains.kotlin.backend.common.serialization.proto.IrConstructorCall> 
      getAnnotationList();
  /**
   * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrConstructorCall annotation = 4;</code>
   */
  org.jetbrains.kotlin.backend.common.serialization.proto.IrConstructorCall getAnnotation(int index);
  /**
   * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.IrConstructorCall annotation = 4;</code>
   */
  int getAnnotationCount();

  /**
   * <code>repeated int64 explicitly_exported_to_compiler = 5 [packed = true];</code>
   */
  java.util.List<java.lang.Long> getExplicitlyExportedToCompilerList();
  /**
   * <code>repeated int64 explicitly_exported_to_compiler = 5 [packed = true];</code>
   */
  int getExplicitlyExportedToCompilerCount();
  /**
   * <code>repeated int64 explicitly_exported_to_compiler = 5 [packed = true];</code>
   */
  long getExplicitlyExportedToCompiler(int index);

  /**
   * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.Actual actual = 6;</code>
   */
  java.util.List<org.jetbrains.kotlin.backend.common.serialization.proto.Actual> 
      getActualList();
  /**
   * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.Actual actual = 6;</code>
   */
  org.jetbrains.kotlin.backend.common.serialization.proto.Actual getActual(int index);
  /**
   * <code>repeated .org.jetbrains.kotlin.backend.common.serialization.proto.Actual actual = 6;</code>
   */
  int getActualCount();

  /**
   * <code>optional int32 identifier = 7;</code>
   *
   * <pre>
   * A number that is unique for each IrFile in the klib.
   * Used to unambiguously refer to files in FileSignatures,
   * since the file's name and package fqname are not enough (KT-50963).
   * </pre>
   */
  boolean hasIdentifier();
  /**
   * <code>optional int32 identifier = 7;</code>
   *
   * <pre>
   * A number that is unique for each IrFile in the klib.
   * Used to unambiguously refer to files in FileSignatures,
   * since the file's name and package fqname are not enough (KT-50963).
   * </pre>
   */
  int getIdentifier();
}